# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gitapi_pb2 as gitapi__pb2


class GitStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Action = channel.unary_unary(
                '/gitapi.Git/Action',
                request_serializer=gitapi__pb2.Command.SerializeToString,
                response_deserializer=gitapi__pb2.CommandResponse.FromString,
                )


class GitServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Action(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GitServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Action': grpc.unary_unary_rpc_method_handler(
                    servicer.Action,
                    request_deserializer=gitapi__pb2.Command.FromString,
                    response_serializer=gitapi__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gitapi.Git', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Git(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Action(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gitapi.Git/Action',
            gitapi__pb2.Command.SerializeToString,
            gitapi__pb2.CommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
