/*
Package ndk-git is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /Users/henderiw/CodeProjects/go/pkg/mod/github.com/openconfig/ygot@v0.8.3/genutil/names.go
using the following YANG input files:
	- ../yang/ndk-git-types.yang
	- ../yang/ndk-git.yang
Imported modules were sourced from:
	- ../../../../goysrl/yang/...
*/
package ndkgit

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
)


// ΛEnum is a map, keyed by the name of the type defined for each enum in the
// generated Go code, which provides a mapping between the constant int64 value
// of each value of the enumeration, and the string that is used to represent it
// in the YANG schema. The map is named ΛEnum in order to avoid clash with any
// valid YANG identifier.
var ΛEnum = map[string]map[int64]ygot.EnumDefinition{
	"E_Git_ActionType": {
		1: {Name: "branch"},
		2: {Name: "commit"},
		3: {Name: "pull-request"},
	},
	"E_Git_OperState": {
		2: {Name: "up"},
		3: {Name: "down"},
		4: {Name: "empty"},
		5: {Name: "downloading"},
		6: {Name: "booting"},
		7: {Name: "starting"},
		8: {Name: "failed"},
		9: {Name: "synchronizing"},
		10: {Name: "upgrading"},
	},
	"E_SrlNokiaBridgeTableMacDuplication_AdminState": {
		2: {Name: "enable"},
		3: {Name: "disable"},
	},
	"E_SrlNokiaBridgeTableMacLearning_AdminState": {
		2: {Name: "enable"},
		3: {Name: "disable"},
	},
	"E_SrlNokiaBridgeTableMacLearning_OperState": {
		2: {Name: "up"},
		3: {Name: "down"},
		4: {Name: "empty"},
		5: {Name: "downloading"},
		6: {Name: "booting"},
		7: {Name: "starting"},
		8: {Name: "failed"},
		9: {Name: "synchronizing"},
		10: {Name: "upgrading"},
	},
	"E_SrlNokiaNetworkInstance_AdminState": {
		2: {Name: "enable"},
		3: {Name: "disable"},
	},
	"E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action": {
		1: {Name: "stop-learning"},
		2: {Name: "blackhole"},
		3: {Name: "oper-down"},
	},
	"E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason": {
		1: {Name: "admin-disabled"},
	},
	"E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name": {
		2: {Name: "dest-unreachable"},
		3: {Name: "packet-too-big"},
		4: {Name: "time-exceeded"},
		5: {Name: "param-problem"},
		129: {Name: "echo-request"},
		130: {Name: "echo-reply"},
		134: {Name: "rtr-solicitation"},
		135: {Name: "rtr-advertisement"},
		136: {Name: "nbr-solicitation"},
		137: {Name: "nbr-advertisement"},
		138: {Name: "redirect"},
	},
	"E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name": {
		1: {Name: "echo-reply"},
		4: {Name: "dest-unreachable"},
		6: {Name: "redirect"},
		9: {Name: "echo"},
		10: {Name: "rtr-advertisement"},
		11: {Name: "rtr-selection"},
		12: {Name: "time-exceeded"},
		13: {Name: "param-problem"},
		14: {Name: "timestamp"},
		15: {Name: "timestamp-reply"},
	},
	"E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason": {
		1: {Name: "ip-addr-missing"},
		2: {Name: "ip-addr-overlap"},
		3: {Name: "subif-down"},
		4: {Name: "net-inst-down"},
		5: {Name: "vrf-type-mismatch"},
		6: {Name: "mac-dup-detected"},
		7: {Name: "associated-mac-vrf-down"},
		8: {Name: "mac-vrf-association-missing"},
		9: {Name: "ip-vrf-association-missing"},
		10: {Name: "associated-ip-vrf-down"},
	},
	"E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason": {
		1: {Name: "routed"},
		2: {Name: "admin-disabled"},
		3: {Name: "mac-dup-detected"},
	},
	"E_SrlNokiaNetworkInstance_NiType": {
		1: {Name: "default", DefiningModule: "srl_nokia-network-instance"},
		2: {Name: "ip-vrf", DefiningModule: "srl_nokia-network-instance"},
		3: {Name: "mac-vrf", DefiningModule: "srl_nokia-network-instance"},
	},
	"E_SrlNokiaNetworkInstance_OperState": {
		2: {Name: "up"},
		3: {Name: "down"},
		4: {Name: "empty"},
		5: {Name: "downloading"},
		6: {Name: "booting"},
		7: {Name: "starting"},
		8: {Name: "failed"},
		9: {Name: "synchronizing"},
		10: {Name: "upgrading"},
	},
}


// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
var ΛEnumTypes = map[string][]reflect.Type{
	"/git/action": []reflect.Type{
		reflect.TypeOf((E_Git_ActionType)(0)),
	},
	"/git/oper-state": []reflect.Type{
		reflect.TypeOf((E_Git_OperState)(0)),
	},
	"/network-instance/admin-state": []reflect.Type{
		reflect.TypeOf((E_SrlNokiaNetworkInstance_AdminState)(0)),
	},
	"/network-instance/bridge-table/mac-duplication/action": []reflect.Type{
		reflect.TypeOf((E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action)(0)),
	},
	"/network-instance/bridge-table/mac-duplication/admin-state": []reflect.Type{
		reflect.TypeOf((E_SrlNokiaBridgeTableMacDuplication_AdminState)(0)),
	},
	"/network-instance/bridge-table/mac-learning/admin-state": []reflect.Type{
		reflect.TypeOf((E_SrlNokiaBridgeTableMacLearning_AdminState)(0)),
	},
	"/network-instance/bridge-table/mac-learning/aging/admin-state": []reflect.Type{
		reflect.TypeOf((E_SrlNokiaBridgeTableMacLearning_AdminState)(0)),
	},
	"/network-instance/bridge-table/mac-learning/oper-mac-learning": []reflect.Type{
		reflect.TypeOf((E_SrlNokiaBridgeTableMacLearning_OperState)(0)),
	},
	"/network-instance/bridge-table/mac-learning/oper-mac-learning-disabled-reason": []reflect.Type{
		reflect.TypeOf((E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason)(0)),
	},
	"/network-instance/icmp/statistics/type/name": []reflect.Type{
		reflect.TypeOf((E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name)(0)),
	},
	"/network-instance/icmp6/statistics/type/name": []reflect.Type{
		reflect.TypeOf((E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name)(0)),
	},
	"/network-instance/interface/oper-down-reason": []reflect.Type{
		reflect.TypeOf((E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason)(0)),
	},
	"/network-instance/interface/oper-mac-learning": []reflect.Type{
		reflect.TypeOf((E_SrlNokiaNetworkInstance_OperState)(0)),
	},
	"/network-instance/interface/oper-mac-learning-disabled-reason": []reflect.Type{
		reflect.TypeOf((E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason)(0)),
	},
	"/network-instance/interface/oper-state": []reflect.Type{
		reflect.TypeOf((E_SrlNokiaNetworkInstance_OperState)(0)),
	},
	"/network-instance/oper-state": []reflect.Type{
		reflect.TypeOf((E_SrlNokiaNetworkInstance_OperState)(0)),
	},
	"/network-instance/type": []reflect.Type{
		reflect.TypeOf((E_SrlNokiaNetworkInstance_NiType)(0)),
	},
}

