/*
Package ndk-git is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /Users/henderiw/CodeProjects/go/pkg/mod/github.com/openconfig/ygot@v0.8.3/genutil/names.go
using the following YANG input files:
	- ../yang/ndk-git-types.yang
	- ../yang/ndk-git.yang
Imported modules were sourced from:
	- ../../../../goysrl/yang/...
*/
package ndk-git

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
)


// E_Git_ActionType is a derived int64 type which is used to represent
// the enumerated node Git_ActionType. An additional value named
// Git_ActionType_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_Git_ActionType int64

// IsYANGGoEnum ensures that Git_ActionType implements the yang.GoEnum
// interface. This ensures that Git_ActionType can be identified as a
// mapped type for a YANG enumeration.
func (E_Git_ActionType) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  Git_ActionType.
func (E_Git_ActionType) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_Git_ActionType.
func (e E_Git_ActionType) String() string {
	return ygot.EnumLogString(e, int64(e), "E_Git_ActionType")
}

const (
	// Git_ActionType_UNSET corresponds to the value UNSET of Git_ActionType
	Git_ActionType_UNSET E_Git_ActionType = 0
	// Git_ActionType_branch corresponds to the value branch of Git_ActionType
	Git_ActionType_branch E_Git_ActionType = 1
	// Git_ActionType_commit corresponds to the value commit of Git_ActionType
	Git_ActionType_commit E_Git_ActionType = 2
	// Git_ActionType_pull_request corresponds to the value pull_request of Git_ActionType
	Git_ActionType_pull_request E_Git_ActionType = 3
)


// E_Git_OperState is a derived int64 type which is used to represent
// the enumerated node Git_OperState. An additional value named
// Git_OperState_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_Git_OperState int64

// IsYANGGoEnum ensures that Git_OperState implements the yang.GoEnum
// interface. This ensures that Git_OperState can be identified as a
// mapped type for a YANG enumeration.
func (E_Git_OperState) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  Git_OperState.
func (E_Git_OperState) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_Git_OperState.
func (e E_Git_OperState) String() string {
	return ygot.EnumLogString(e, int64(e), "E_Git_OperState")
}

const (
	// Git_OperState_UNSET corresponds to the value UNSET of Git_OperState
	Git_OperState_UNSET E_Git_OperState = 0
	// Git_OperState_up corresponds to the value up of Git_OperState
	Git_OperState_up E_Git_OperState = 2
	// Git_OperState_down corresponds to the value down of Git_OperState
	Git_OperState_down E_Git_OperState = 3
	// Git_OperState_empty corresponds to the value empty of Git_OperState
	Git_OperState_empty E_Git_OperState = 4
	// Git_OperState_downloading corresponds to the value downloading of Git_OperState
	Git_OperState_downloading E_Git_OperState = 5
	// Git_OperState_booting corresponds to the value booting of Git_OperState
	Git_OperState_booting E_Git_OperState = 6
	// Git_OperState_starting corresponds to the value starting of Git_OperState
	Git_OperState_starting E_Git_OperState = 7
	// Git_OperState_failed corresponds to the value failed of Git_OperState
	Git_OperState_failed E_Git_OperState = 8
	// Git_OperState_synchronizing corresponds to the value synchronizing of Git_OperState
	Git_OperState_synchronizing E_Git_OperState = 9
	// Git_OperState_upgrading corresponds to the value upgrading of Git_OperState
	Git_OperState_upgrading E_Git_OperState = 10
)


// E_SrlNokiaBridgeTableMacDuplication_AdminState is a derived int64 type which is used to represent
// the enumerated node SrlNokiaBridgeTableMacDuplication_AdminState. An additional value named
// SrlNokiaBridgeTableMacDuplication_AdminState_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_SrlNokiaBridgeTableMacDuplication_AdminState int64

// IsYANGGoEnum ensures that SrlNokiaBridgeTableMacDuplication_AdminState implements the yang.GoEnum
// interface. This ensures that SrlNokiaBridgeTableMacDuplication_AdminState can be identified as a
// mapped type for a YANG enumeration.
func (E_SrlNokiaBridgeTableMacDuplication_AdminState) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  SrlNokiaBridgeTableMacDuplication_AdminState.
func (E_SrlNokiaBridgeTableMacDuplication_AdminState) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_SrlNokiaBridgeTableMacDuplication_AdminState.
func (e E_SrlNokiaBridgeTableMacDuplication_AdminState) String() string {
	return ygot.EnumLogString(e, int64(e), "E_SrlNokiaBridgeTableMacDuplication_AdminState")
}

const (
	// SrlNokiaBridgeTableMacDuplication_AdminState_UNSET corresponds to the value UNSET of SrlNokiaBridgeTableMacDuplication_AdminState
	SrlNokiaBridgeTableMacDuplication_AdminState_UNSET E_SrlNokiaBridgeTableMacDuplication_AdminState = 0
	// SrlNokiaBridgeTableMacDuplication_AdminState_enable corresponds to the value enable of SrlNokiaBridgeTableMacDuplication_AdminState
	SrlNokiaBridgeTableMacDuplication_AdminState_enable E_SrlNokiaBridgeTableMacDuplication_AdminState = 2
	// SrlNokiaBridgeTableMacDuplication_AdminState_disable corresponds to the value disable of SrlNokiaBridgeTableMacDuplication_AdminState
	SrlNokiaBridgeTableMacDuplication_AdminState_disable E_SrlNokiaBridgeTableMacDuplication_AdminState = 3
)


// E_SrlNokiaBridgeTableMacLearning_AdminState is a derived int64 type which is used to represent
// the enumerated node SrlNokiaBridgeTableMacLearning_AdminState. An additional value named
// SrlNokiaBridgeTableMacLearning_AdminState_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_SrlNokiaBridgeTableMacLearning_AdminState int64

// IsYANGGoEnum ensures that SrlNokiaBridgeTableMacLearning_AdminState implements the yang.GoEnum
// interface. This ensures that SrlNokiaBridgeTableMacLearning_AdminState can be identified as a
// mapped type for a YANG enumeration.
func (E_SrlNokiaBridgeTableMacLearning_AdminState) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  SrlNokiaBridgeTableMacLearning_AdminState.
func (E_SrlNokiaBridgeTableMacLearning_AdminState) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_SrlNokiaBridgeTableMacLearning_AdminState.
func (e E_SrlNokiaBridgeTableMacLearning_AdminState) String() string {
	return ygot.EnumLogString(e, int64(e), "E_SrlNokiaBridgeTableMacLearning_AdminState")
}

const (
	// SrlNokiaBridgeTableMacLearning_AdminState_UNSET corresponds to the value UNSET of SrlNokiaBridgeTableMacLearning_AdminState
	SrlNokiaBridgeTableMacLearning_AdminState_UNSET E_SrlNokiaBridgeTableMacLearning_AdminState = 0
	// SrlNokiaBridgeTableMacLearning_AdminState_enable corresponds to the value enable of SrlNokiaBridgeTableMacLearning_AdminState
	SrlNokiaBridgeTableMacLearning_AdminState_enable E_SrlNokiaBridgeTableMacLearning_AdminState = 2
	// SrlNokiaBridgeTableMacLearning_AdminState_disable corresponds to the value disable of SrlNokiaBridgeTableMacLearning_AdminState
	SrlNokiaBridgeTableMacLearning_AdminState_disable E_SrlNokiaBridgeTableMacLearning_AdminState = 3
)


// E_SrlNokiaBridgeTableMacLearning_OperState is a derived int64 type which is used to represent
// the enumerated node SrlNokiaBridgeTableMacLearning_OperState. An additional value named
// SrlNokiaBridgeTableMacLearning_OperState_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_SrlNokiaBridgeTableMacLearning_OperState int64

// IsYANGGoEnum ensures that SrlNokiaBridgeTableMacLearning_OperState implements the yang.GoEnum
// interface. This ensures that SrlNokiaBridgeTableMacLearning_OperState can be identified as a
// mapped type for a YANG enumeration.
func (E_SrlNokiaBridgeTableMacLearning_OperState) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  SrlNokiaBridgeTableMacLearning_OperState.
func (E_SrlNokiaBridgeTableMacLearning_OperState) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_SrlNokiaBridgeTableMacLearning_OperState.
func (e E_SrlNokiaBridgeTableMacLearning_OperState) String() string {
	return ygot.EnumLogString(e, int64(e), "E_SrlNokiaBridgeTableMacLearning_OperState")
}

const (
	// SrlNokiaBridgeTableMacLearning_OperState_UNSET corresponds to the value UNSET of SrlNokiaBridgeTableMacLearning_OperState
	SrlNokiaBridgeTableMacLearning_OperState_UNSET E_SrlNokiaBridgeTableMacLearning_OperState = 0
	// SrlNokiaBridgeTableMacLearning_OperState_up corresponds to the value up of SrlNokiaBridgeTableMacLearning_OperState
	SrlNokiaBridgeTableMacLearning_OperState_up E_SrlNokiaBridgeTableMacLearning_OperState = 2
	// SrlNokiaBridgeTableMacLearning_OperState_down corresponds to the value down of SrlNokiaBridgeTableMacLearning_OperState
	SrlNokiaBridgeTableMacLearning_OperState_down E_SrlNokiaBridgeTableMacLearning_OperState = 3
	// SrlNokiaBridgeTableMacLearning_OperState_empty corresponds to the value empty of SrlNokiaBridgeTableMacLearning_OperState
	SrlNokiaBridgeTableMacLearning_OperState_empty E_SrlNokiaBridgeTableMacLearning_OperState = 4
	// SrlNokiaBridgeTableMacLearning_OperState_downloading corresponds to the value downloading of SrlNokiaBridgeTableMacLearning_OperState
	SrlNokiaBridgeTableMacLearning_OperState_downloading E_SrlNokiaBridgeTableMacLearning_OperState = 5
	// SrlNokiaBridgeTableMacLearning_OperState_booting corresponds to the value booting of SrlNokiaBridgeTableMacLearning_OperState
	SrlNokiaBridgeTableMacLearning_OperState_booting E_SrlNokiaBridgeTableMacLearning_OperState = 6
	// SrlNokiaBridgeTableMacLearning_OperState_starting corresponds to the value starting of SrlNokiaBridgeTableMacLearning_OperState
	SrlNokiaBridgeTableMacLearning_OperState_starting E_SrlNokiaBridgeTableMacLearning_OperState = 7
	// SrlNokiaBridgeTableMacLearning_OperState_failed corresponds to the value failed of SrlNokiaBridgeTableMacLearning_OperState
	SrlNokiaBridgeTableMacLearning_OperState_failed E_SrlNokiaBridgeTableMacLearning_OperState = 8
	// SrlNokiaBridgeTableMacLearning_OperState_synchronizing corresponds to the value synchronizing of SrlNokiaBridgeTableMacLearning_OperState
	SrlNokiaBridgeTableMacLearning_OperState_synchronizing E_SrlNokiaBridgeTableMacLearning_OperState = 9
	// SrlNokiaBridgeTableMacLearning_OperState_upgrading corresponds to the value upgrading of SrlNokiaBridgeTableMacLearning_OperState
	SrlNokiaBridgeTableMacLearning_OperState_upgrading E_SrlNokiaBridgeTableMacLearning_OperState = 10
)


// E_SrlNokiaNetworkInstance_AdminState is a derived int64 type which is used to represent
// the enumerated node SrlNokiaNetworkInstance_AdminState. An additional value named
// SrlNokiaNetworkInstance_AdminState_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_SrlNokiaNetworkInstance_AdminState int64

// IsYANGGoEnum ensures that SrlNokiaNetworkInstance_AdminState implements the yang.GoEnum
// interface. This ensures that SrlNokiaNetworkInstance_AdminState can be identified as a
// mapped type for a YANG enumeration.
func (E_SrlNokiaNetworkInstance_AdminState) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  SrlNokiaNetworkInstance_AdminState.
func (E_SrlNokiaNetworkInstance_AdminState) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_SrlNokiaNetworkInstance_AdminState.
func (e E_SrlNokiaNetworkInstance_AdminState) String() string {
	return ygot.EnumLogString(e, int64(e), "E_SrlNokiaNetworkInstance_AdminState")
}

const (
	// SrlNokiaNetworkInstance_AdminState_UNSET corresponds to the value UNSET of SrlNokiaNetworkInstance_AdminState
	SrlNokiaNetworkInstance_AdminState_UNSET E_SrlNokiaNetworkInstance_AdminState = 0
	// SrlNokiaNetworkInstance_AdminState_enable corresponds to the value enable of SrlNokiaNetworkInstance_AdminState
	SrlNokiaNetworkInstance_AdminState_enable E_SrlNokiaNetworkInstance_AdminState = 2
	// SrlNokiaNetworkInstance_AdminState_disable corresponds to the value disable of SrlNokiaNetworkInstance_AdminState
	SrlNokiaNetworkInstance_AdminState_disable E_SrlNokiaNetworkInstance_AdminState = 3
)


// E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action is a derived int64 type which is used to represent
// the enumerated node SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action. An additional value named
// SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action int64

// IsYANGGoEnum ensures that SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action implements the yang.GoEnum
// interface. This ensures that SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action can be identified as a
// mapped type for a YANG enumeration.
func (E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action.
func (E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action.
func (e E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action) String() string {
	return ygot.EnumLogString(e, int64(e), "E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action")
}

const (
	// SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action_UNSET corresponds to the value UNSET of SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action
	SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action_UNSET E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action = 0
	// SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action_stop_learning corresponds to the value stop_learning of SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action
	SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action_stop_learning E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action = 1
	// SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action_blackhole corresponds to the value blackhole of SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action
	SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action_blackhole E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action = 2
	// SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action_oper_down corresponds to the value oper_down of SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action
	SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action_oper_down E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacDuplication_Action = 3
)


// E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason is a derived int64 type which is used to represent
// the enumerated node SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason. An additional value named
// SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason int64

// IsYANGGoEnum ensures that SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason implements the yang.GoEnum
// interface. This ensures that SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason can be identified as a
// mapped type for a YANG enumeration.
func (E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason.
func (E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason.
func (e E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason) String() string {
	return ygot.EnumLogString(e, int64(e), "E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason")
}

const (
	// SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason_UNSET corresponds to the value UNSET of SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason
	SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason_UNSET E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason = 0
	// SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason_admin_disabled corresponds to the value admin_disabled of SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason
	SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason_admin_disabled E_SrlNokiaNetworkInstance_NetworkInstance_BridgeTable_MacLearning_OperMacLearningDisabledReason = 1
)


// E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name is a derived int64 type which is used to represent
// the enumerated node SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name. An additional value named
// SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name int64

// IsYANGGoEnum ensures that SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name implements the yang.GoEnum
// interface. This ensures that SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name can be identified as a
// mapped type for a YANG enumeration.
func (E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name.
func (E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name.
func (e E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name) String() string {
	return ygot.EnumLogString(e, int64(e), "E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name")
}

const (
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_UNSET corresponds to the value UNSET of SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_UNSET E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name = 0
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_dest_unreachable corresponds to the value dest_unreachable of SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_dest_unreachable E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name = 2
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_packet_too_big corresponds to the value packet_too_big of SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_packet_too_big E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name = 3
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_time_exceeded corresponds to the value time_exceeded of SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_time_exceeded E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name = 4
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_param_problem corresponds to the value param_problem of SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_param_problem E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name = 5
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_echo_request corresponds to the value echo_request of SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_echo_request E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name = 129
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_echo_reply corresponds to the value echo_reply of SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_echo_reply E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name = 130
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_rtr_solicitation corresponds to the value rtr_solicitation of SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_rtr_solicitation E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name = 134
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_rtr_advertisement corresponds to the value rtr_advertisement of SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_rtr_advertisement E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name = 135
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_nbr_solicitation corresponds to the value nbr_solicitation of SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_nbr_solicitation E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name = 136
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_nbr_advertisement corresponds to the value nbr_advertisement of SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_nbr_advertisement E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name = 137
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_redirect corresponds to the value redirect of SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name_redirect E_SrlNokiaNetworkInstance_NetworkInstance_Icmp6_Statistics_Type_Name = 138
)


// E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name is a derived int64 type which is used to represent
// the enumerated node SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name. An additional value named
// SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name int64

// IsYANGGoEnum ensures that SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name implements the yang.GoEnum
// interface. This ensures that SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name can be identified as a
// mapped type for a YANG enumeration.
func (E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name.
func (E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name.
func (e E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name) String() string {
	return ygot.EnumLogString(e, int64(e), "E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name")
}

const (
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_UNSET corresponds to the value UNSET of SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_UNSET E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name = 0
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_echo_reply corresponds to the value echo_reply of SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_echo_reply E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name = 1
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_dest_unreachable corresponds to the value dest_unreachable of SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_dest_unreachable E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name = 4
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_redirect corresponds to the value redirect of SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_redirect E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name = 6
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_echo corresponds to the value echo of SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_echo E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name = 9
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_rtr_advertisement corresponds to the value rtr_advertisement of SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_rtr_advertisement E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name = 10
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_rtr_selection corresponds to the value rtr_selection of SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_rtr_selection E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name = 11
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_time_exceeded corresponds to the value time_exceeded of SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_time_exceeded E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name = 12
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_param_problem corresponds to the value param_problem of SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_param_problem E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name = 13
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_timestamp corresponds to the value timestamp of SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_timestamp E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name = 14
	// SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_timestamp_reply corresponds to the value timestamp_reply of SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name
	SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name_timestamp_reply E_SrlNokiaNetworkInstance_NetworkInstance_Icmp_Statistics_Type_Name = 15
)


// E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason is a derived int64 type which is used to represent
// the enumerated node SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason. An additional value named
// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason int64

// IsYANGGoEnum ensures that SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason implements the yang.GoEnum
// interface. This ensures that SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason can be identified as a
// mapped type for a YANG enumeration.
func (E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason.
func (E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason.
func (e E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason) String() string {
	return ygot.EnumLogString(e, int64(e), "E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason")
}

const (
	// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_UNSET corresponds to the value UNSET of SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason
	SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_UNSET E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason = 0
	// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_ip_addr_missing corresponds to the value ip_addr_missing of SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason
	SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_ip_addr_missing E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason = 1
	// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_ip_addr_overlap corresponds to the value ip_addr_overlap of SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason
	SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_ip_addr_overlap E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason = 2
	// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_subif_down corresponds to the value subif_down of SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason
	SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_subif_down E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason = 3
	// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_net_inst_down corresponds to the value net_inst_down of SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason
	SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_net_inst_down E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason = 4
	// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_vrf_type_mismatch corresponds to the value vrf_type_mismatch of SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason
	SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_vrf_type_mismatch E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason = 5
	// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_mac_dup_detected corresponds to the value mac_dup_detected of SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason
	SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_mac_dup_detected E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason = 6
	// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_associated_mac_vrf_down corresponds to the value associated_mac_vrf_down of SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason
	SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_associated_mac_vrf_down E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason = 7
	// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_mac_vrf_association_missing corresponds to the value mac_vrf_association_missing of SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason
	SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_mac_vrf_association_missing E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason = 8
	// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_ip_vrf_association_missing corresponds to the value ip_vrf_association_missing of SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason
	SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_ip_vrf_association_missing E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason = 9
	// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_associated_ip_vrf_down corresponds to the value associated_ip_vrf_down of SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason
	SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason_associated_ip_vrf_down E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperDownReason = 10
)


// E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason is a derived int64 type which is used to represent
// the enumerated node SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason. An additional value named
// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason int64

// IsYANGGoEnum ensures that SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason implements the yang.GoEnum
// interface. This ensures that SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason can be identified as a
// mapped type for a YANG enumeration.
func (E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason.
func (E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason.
func (e E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason) String() string {
	return ygot.EnumLogString(e, int64(e), "E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason")
}

const (
	// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason_UNSET corresponds to the value UNSET of SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason
	SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason_UNSET E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason = 0
	// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason_routed corresponds to the value routed of SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason
	SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason_routed E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason = 1
	// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason_admin_disabled corresponds to the value admin_disabled of SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason
	SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason_admin_disabled E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason = 2
	// SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason_mac_dup_detected corresponds to the value mac_dup_detected of SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason
	SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason_mac_dup_detected E_SrlNokiaNetworkInstance_NetworkInstance_Interface_OperMacLearningDisabledReason = 3
)


// E_SrlNokiaNetworkInstance_NiType is a derived int64 type which is used to represent
// the enumerated node SrlNokiaNetworkInstance_NiType. An additional value named
// SrlNokiaNetworkInstance_NiType_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_SrlNokiaNetworkInstance_NiType int64

// IsYANGGoEnum ensures that SrlNokiaNetworkInstance_NiType implements the yang.GoEnum
// interface. This ensures that SrlNokiaNetworkInstance_NiType can be identified as a
// mapped type for a YANG enumeration.
func (E_SrlNokiaNetworkInstance_NiType) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  SrlNokiaNetworkInstance_NiType.
func (E_SrlNokiaNetworkInstance_NiType) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_SrlNokiaNetworkInstance_NiType.
func (e E_SrlNokiaNetworkInstance_NiType) String() string {
	return ygot.EnumLogString(e, int64(e), "E_SrlNokiaNetworkInstance_NiType")
}

const (
	// SrlNokiaNetworkInstance_NiType_UNSET corresponds to the value UNSET of SrlNokiaNetworkInstance_NiType
	SrlNokiaNetworkInstance_NiType_UNSET E_SrlNokiaNetworkInstance_NiType = 0
	// SrlNokiaNetworkInstance_NiType_default corresponds to the value default of SrlNokiaNetworkInstance_NiType
	SrlNokiaNetworkInstance_NiType_default E_SrlNokiaNetworkInstance_NiType = 1
	// SrlNokiaNetworkInstance_NiType_ip_vrf corresponds to the value ip_vrf of SrlNokiaNetworkInstance_NiType
	SrlNokiaNetworkInstance_NiType_ip_vrf E_SrlNokiaNetworkInstance_NiType = 2
	// SrlNokiaNetworkInstance_NiType_mac_vrf corresponds to the value mac_vrf of SrlNokiaNetworkInstance_NiType
	SrlNokiaNetworkInstance_NiType_mac_vrf E_SrlNokiaNetworkInstance_NiType = 3
)


// E_SrlNokiaNetworkInstance_OperState is a derived int64 type which is used to represent
// the enumerated node SrlNokiaNetworkInstance_OperState. An additional value named
// SrlNokiaNetworkInstance_OperState_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_SrlNokiaNetworkInstance_OperState int64

// IsYANGGoEnum ensures that SrlNokiaNetworkInstance_OperState implements the yang.GoEnum
// interface. This ensures that SrlNokiaNetworkInstance_OperState can be identified as a
// mapped type for a YANG enumeration.
func (E_SrlNokiaNetworkInstance_OperState) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  SrlNokiaNetworkInstance_OperState.
func (E_SrlNokiaNetworkInstance_OperState) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_SrlNokiaNetworkInstance_OperState.
func (e E_SrlNokiaNetworkInstance_OperState) String() string {
	return ygot.EnumLogString(e, int64(e), "E_SrlNokiaNetworkInstance_OperState")
}

const (
	// SrlNokiaNetworkInstance_OperState_UNSET corresponds to the value UNSET of SrlNokiaNetworkInstance_OperState
	SrlNokiaNetworkInstance_OperState_UNSET E_SrlNokiaNetworkInstance_OperState = 0
	// SrlNokiaNetworkInstance_OperState_up corresponds to the value up of SrlNokiaNetworkInstance_OperState
	SrlNokiaNetworkInstance_OperState_up E_SrlNokiaNetworkInstance_OperState = 2
	// SrlNokiaNetworkInstance_OperState_down corresponds to the value down of SrlNokiaNetworkInstance_OperState
	SrlNokiaNetworkInstance_OperState_down E_SrlNokiaNetworkInstance_OperState = 3
	// SrlNokiaNetworkInstance_OperState_empty corresponds to the value empty of SrlNokiaNetworkInstance_OperState
	SrlNokiaNetworkInstance_OperState_empty E_SrlNokiaNetworkInstance_OperState = 4
	// SrlNokiaNetworkInstance_OperState_downloading corresponds to the value downloading of SrlNokiaNetworkInstance_OperState
	SrlNokiaNetworkInstance_OperState_downloading E_SrlNokiaNetworkInstance_OperState = 5
	// SrlNokiaNetworkInstance_OperState_booting corresponds to the value booting of SrlNokiaNetworkInstance_OperState
	SrlNokiaNetworkInstance_OperState_booting E_SrlNokiaNetworkInstance_OperState = 6
	// SrlNokiaNetworkInstance_OperState_starting corresponds to the value starting of SrlNokiaNetworkInstance_OperState
	SrlNokiaNetworkInstance_OperState_starting E_SrlNokiaNetworkInstance_OperState = 7
	// SrlNokiaNetworkInstance_OperState_failed corresponds to the value failed of SrlNokiaNetworkInstance_OperState
	SrlNokiaNetworkInstance_OperState_failed E_SrlNokiaNetworkInstance_OperState = 8
	// SrlNokiaNetworkInstance_OperState_synchronizing corresponds to the value synchronizing of SrlNokiaNetworkInstance_OperState
	SrlNokiaNetworkInstance_OperState_synchronizing E_SrlNokiaNetworkInstance_OperState = 9
	// SrlNokiaNetworkInstance_OperState_upgrading corresponds to the value upgrading of SrlNokiaNetworkInstance_OperState
	SrlNokiaNetworkInstance_OperState_upgrading E_SrlNokiaNetworkInstance_OperState = 10
)

