/*
Package ndk-git is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /Users/henderiw/CodeProjects/go/pkg/mod/github.com/openconfig/ygot@v0.8.3/genutil/names.go
using the following YANG input files:
	- ../yang/ndk-git-types.yang
	- ../yang/ndk-git.yang
Imported modules were sourced from:
	- ../../../../goysrl/yang/...
*/
package ndk-git

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
)


// Git_Git represents the /git/git YANG schema element.
type Git_Git struct {
	Action	E_Git_ActionType	`path:"action" module:"git"`
	Author	*string	`path:"author" module:"git"`
	AuthorEmail	*string	`path:"author-email" module:"git"`
	Branch	*string	`path:"branch" module:"git"`
	File	*string	`path:"file" module:"git"`
	NetworkInstance	*string	`path:"network-instance" module:"git"`
	OperState	E_Git_OperState	`path:"oper-state" module:"git"`
	Organization	*string	`path:"organization" module:"git"`
	Owner	*string	`path:"owner" module:"git"`
	Repo	*string	`path:"repo" module:"git"`
	Statistics	*Git_Git_Statistics	`path:"statistics" module:"git"`
	Token	*string	`path:"token" module:"git"`
}

// IsYANGGoStruct ensures that Git_Git implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Git_Git) IsYANGGoStruct() {}


// Git_Git_Statistics represents the /git/git/statistics YANG schema element.
type Git_Git_Statistics struct {
	Failure	*uint64	`path:"failure" module:"git"`
	Success	*uint64	`path:"success" module:"git"`
}

// IsYANGGoStruct ensures that Git_Git_Statistics implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Git_Git_Statistics) IsYANGGoStruct() {}


