/*
Package ndkygit is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /Users/henderiw/CodeProjects/go/pkg/mod/github.com/openconfig/ygot@v0.8.3/genutil/names.go
using the following YANG input files:
	- ../yang/ndk-git.yang
	- ../yang/srl_nokia-common.yang
Imported modules were sourced from:
	- ../yang/...
*/
package ndkygit
