/*
Package ndk-git is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /Users/henderiw/CodeProjects/go/pkg/mod/github.com/openconfig/ygot@v0.8.3/genutil/names.go
using the following YANG input files:
	- ../yang/ndk-git.yang
	- ../yang/srl_nokia-common.yang
Imported modules were sourced from:
	- ../yang/...
*/
package ndk-git

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
)


// E_Git_OperState is a derived int64 type which is used to represent
// the enumerated node Git_OperState. An additional value named
// Git_OperState_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_Git_OperState int64

// IsYANGGoEnum ensures that Git_OperState implements the yang.GoEnum
// interface. This ensures that Git_OperState can be identified as a
// mapped type for a YANG enumeration.
func (E_Git_OperState) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  Git_OperState.
func (E_Git_OperState) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_Git_OperState.
func (e E_Git_OperState) String() string {
	return ygot.EnumLogString(e, int64(e), "E_Git_OperState")
}

const (
	// Git_OperState_UNSET corresponds to the value UNSET of Git_OperState
	Git_OperState_UNSET E_Git_OperState = 0
	// Git_OperState_up corresponds to the value up of Git_OperState
	Git_OperState_up E_Git_OperState = 2
	// Git_OperState_down corresponds to the value down of Git_OperState
	Git_OperState_down E_Git_OperState = 3
	// Git_OperState_empty corresponds to the value empty of Git_OperState
	Git_OperState_empty E_Git_OperState = 4
	// Git_OperState_downloading corresponds to the value downloading of Git_OperState
	Git_OperState_downloading E_Git_OperState = 5
	// Git_OperState_booting corresponds to the value booting of Git_OperState
	Git_OperState_booting E_Git_OperState = 6
	// Git_OperState_starting corresponds to the value starting of Git_OperState
	Git_OperState_starting E_Git_OperState = 7
	// Git_OperState_failed corresponds to the value failed of Git_OperState
	Git_OperState_failed E_Git_OperState = 8
	// Git_OperState_synchronizing corresponds to the value synchronizing of Git_OperState
	Git_OperState_synchronizing E_Git_OperState = 9
	// Git_OperState_upgrading corresponds to the value upgrading of Git_OperState
	Git_OperState_upgrading E_Git_OperState = 10
)

